name: Docker CI

# for now build only new tags
on:
  push:
    branches:
    #   - 'master'
      - 'feature/migrate-to-aws'    
    tags:
      - 'v*'
  # pull_request:
  #   branches:
  #     - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      imagetag: ${{ steps.first.outputs.imagetag }}

    steps:

    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Observability
      uses: kvrhdn/gha-buildevents@v1
      with:
        apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
        dataset: continuous-deployment

        # Required: the job status, this will be used in the post section and sent
        # as status of the trace. Must always be ${{ job.status }}.
        job-status: ${{ job.status }}

        # Optional: this should only be used in combination with matrix builds. Set
        # this to a value uniquely describing each matrix configuration.
        matrix-key: ${{ matrix.value }}

    - name: Prepare
      id: prep
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        IMAGE="registry.aws.abraham.fun/abraham-ai/eden-clip"
        echo ::set-output name=tagged_image::${IMAGE}:${TAG}
        echo ::set-output name=tag::${TAG}
        echo ::set-output name=image::${IMAGE}

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'       
      uses: docker/login-action@v1
      with:
          registry: registry.aws.abraham.fun
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true #${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.prep.outputs.tagged_image }}

    - name: Pick up one tag
      id: first
      run: |
        IMAGE=$(echo "${{ steps.meta.outputs.tags }}" | sed 1q)
        echo "::set-output name=imagetag::$IMAGE"

  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Check out releases repo
        uses: actions/checkout@v2
        with:
          repository: abraham-ai/releases
          ref: refs/heads/main
          token: ${{ secrets.ONE1ZERO1ONE_PAT }}
      
      - name: Bump up eden-staging image
        run: |
          sed -i -E "s@registry.aws.abraham.fun/abraham-ai/eden-clip:.*@${{ needs.prep.outputs.tagged_image }}@" releases/apps/eden/eden-clip-stg/deployment-eden-clip.yaml
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Abraham Releases"
          git commit -am "Bump eden-staging"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: abraham-ai/releases
          branch: refs/heads/main
          github_token: ${{ secrets.ONE1ZERO1ONE_PAT }}   